# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2016-09-09 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='complete',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='service',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
