# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2016-09-21 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0002_auto_20160910_0148'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='name',
            field=models.CharField(default='morning', max_length=250),
            preserve_default=False,
        ),
    ]
